### PR TITLE
Made the project mobile responsive Fixes: Issue #1

### PR DESCRIPTION
**Pull request by MSTEWARDSON**
I have added functionality to support mobile devices. When the screen becomes too small to have both the playlist and search content there is now a button to switch between each page.

Please let me know if there is any issues and or suggestions to add.

Thanks,
Matt

### CODE REVIEW

**Comment by AggRag** [comment]
Great Work @MSTEWARDSON

**Comment by AggRag** [comment]
In mobile view, the Back to Playlist window auto stretches down making user unable to search for something, try to fix it
You can check it here by opening the link in mobile http://unbecoming-cough.surge.sh/

**Comment by AggRag** [comment]
Also, as user clicks on Add to Playlist it should auto play the music and take user to playlist section automatically if on mobile, please let me know if you can do it.

**Comment by MSTEWARDSON** [comment]
Oh sorry, I'll look into that stretching issue. And sure I'll try to add the auto play for mobile feature.

**Comment by MSTEWARDSON** [comment]
Alright so I've made some progress. The stretching issue should be fixed now and while using mobile you are now auto directed to the playlist tab when selecting a track. Issue I'm currently having is actually auto playing the track. As far as I understand I need to use SC.stream() to then call play() but so far I haven't gotten it too work. Do you have any ideas or suggestions for this?

**Comment by AggRag** [comment]
Actually, instead of streaming, I have embedded Sound Cloud widget in order to play music but even when auto_play is true, it is not working because on widget it asks user whether to play in browser or sound cloud, no need to stream music as this widget is fine as of now.

**Comment by AggRag** [comment]
You can find more details here https://developers.soundcloud.com/docs/api/guide#playing

**Comment by MSTEWARDSON** [comment]
Ok, so would you just like me to make a PR for the stretching fix and the redirect to playlist addition?

**Pull request merged**
